platform :ios, '13.0'
source 'https://github.com/CocoaPods/Specs.git'
#source 'https://github.com/adamaszhu/CombineFoundationSpecs.git'

target 'CombineFoundationSample' do
  #pod 'CombineFoundation', '~> 0.1.0'
  pod 'CombineFoundation', :path => '../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    puts "#{target.name}"
  end
end
