default_platform(:ios)

platform :ios do

  project_path = "iCombine.xcodeproj"
  pod_path = "iCombine.podspec"

  before_all do
    ENV['FL_VERSION_NUMBER_PROJECT'] = project_path
    ENV['FL_BUILD_NUMBER_PROJECT'] = project_path
  end

  desc "Set the version"
  lane :set_version do |options|
    version = version_bump_podspec(path: pod_path, version_number: options[:version])
  end
end
