platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'iCombineUtility' do
    pod 'iCombine', '~> 0.3.5'

    target 'CombineUtilityTests' do
        inherit! :search_paths
        pod 'iCombine', '~> 0.3.5'
        pod 'Quick'
        pod 'Nimble'
    end

    target 'iCombineUtilityTests' do
        inherit! :search_paths
        pod 'iCombine', '~> 0.3.5'
        pod 'Quick'
        pod 'Nimble'
    end
end
