#!/bin/bash

NAME=$1

if ! gem spec jazzy > /dev/null 2>&1; then
  sudo gem install jazzy
fi

mv README.md README.md.backup
cp $NAME/README.md README.md

jazzy --clean --module $NAME --build-tool-arguments -project,iCombine.xcodeproj,-scheme,$NAME

mv README.md.backup README.md
